# Stages
stages:
  - build
  - package
  - deploy

# Jobs
maven_build:
  stage: build
  image: maven:3.8.3-openjdk-17
  script: mvn compile

maven_package:
  stage: package
  image: maven:3.8.3-openjdk-17
  script: mvn clean package
  artifacts:
    paths:
      - target/*.jar

docker_package:
  stage: package
  needs: ["maven_package"]
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USERNAME/springapp:latest .
    - docker push $DOCKER_USERNAME/springapp:latest

deploy_to_cluster:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID
    - az aks get-credentials --resource-group Rg-AKS --name myAKSCluster
    - az aks install-cli
    - kubectl apply -f deployment.yml
    - kubectl apply -f service.yml
    - kubectl get services
